
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-6pm-4
owner: ucsb-cs156-w24
repo_name: team01-w24-6pm-4
pull_requests: [{"author":{"id":"U_kgDOBYEHjQ","is_bot":false,"login":"golo230","name":"Derek"},"headRefName":"golo230-patch-1","number":27,"title":"Update README.md","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-4/pull/27"},{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-UniversityQuery-Service-Controller","number":26,"title":"Add UniversityQuery Controller and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-4/pull/26"},{"author":{"id":"U_kgDOBtxmKA","is_bot":false,"login":"Aavash-Adhikari","name":""},"headRefName":"AA-JokeQuery-Service","number":25,"title":"Aavash joke query service ","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-4/pull/25"},{"author":{"id":"MDQ6VXNlcjM4OTAxMzc1","is_bot":false,"login":"luxiangzh","name":"Luxiang Zhang"},"headRefName":"LZ-UniversityQuery-Service","number":24,"title":"Add UniversityQuery Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-6pm-4/pull/24"}]
